### ISSUE TITLE
npm run dev is not working

### ISSUE THREAD

**Issue by murtyk** [cloworm/regex-playground-nextjs#9]
when I tried npm run dev, getting this error

```
Murty-Korada-Mac:regex-playground-nextjs murty$ npm run dev

> nextjs@0.1.0 dev /Users/murty/regex-playground-nextjs
> next dev

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
(node:80285) ExperimentalWarning: The fs.promises API is experimental
error - ./node_modules/tailwindcss/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-5-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-5-2!./node_modules/tailwindcss/tailwind.css)
TypeError: Object.entries(...).flatMap is not a function
    at Array.forEach (<anonymous>)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/tailwindcss/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-5-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-5-2!./node_modules/tailwindcss/tailwind.css)
TypeError: getProcessedPlugins is not a function
{ Error: Cannot find module '/Users/murty/regex-playground-nextjs/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadComponents (/Users/murty/regex-playground-nextjs/node_modules/next/dist/next-server/server/load-components.js:1:1097)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by TSMMark** [comment]
https://stackoverflow.com/a/64909657/2696867

Looks like you need a later version of node >= 11
